module.exports.userAuthRegister =  require('./users-auth/user-register')
module.exports.userAuthLogin =  require('./users-auth/user-login')
module.exports.userAuthLogout =  require('./users-auth/user-logout')
module.exports.presensiDashboard =  require('./presensi/presensi-dashboard')
module.exports.presensiIn =  require('./presensi/presensi-in')
module.exports.presensiOut =  require('./presensi/presensi-out')
module.exports.presensiHistory =  require('./presensi/presensi-history')
module.exports.presensiProfile =  require('./presensi/presensi-profil')